# Generated by Django 5.1.2 on 2024-11-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_options_alter_seller_options_and_more'),
        ('account', '0002_auto_20241126_1358'),
    ]

    operations = [
    ]
