# Generated by Django 5.1.2 on 2024-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_order_order_status_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Shipping', 'shipped'), ('delivered', 'Deliverd')], default='pending', max_length=20),
        ),
    ]
