# Generated by Django 5.1.2 on 2024-11-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_title'),
        ('product', '0003_alter_order_order_status'),
    ]

    operations = [
    ]
